"use client";
// import Navbar from "@/components/Navbar";
// import PageLoader from "@/components/animation/PageLoader";
import { RouteChangeProvider } from "@/contexts/RouteChangedContext";
import { Inter } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";

const Navbar = dynamic(() => import("@/components/Navbar"), {
	ssr: false,
});
const PageLoader = dynamic(() => import("@/components/animation/PageLoader"), {
	ssr: false,
});
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<head>
				<link rel="stylesheet" type="text/css" href="/fonts/style.css" />
			</head>
			<RouteChangeProvider>
				<Navbar />
				<body className={inter.className}>{children}</body>
				<PageLoader />
			</RouteChangeProvider>
		</html>
	);
}
